### ISSUE TITLE
Test TensorFlow-gpu container in nvidia-docker extension on gpu-enabled ec2 instance

### ISSUE THREAD

**Issue by jimthompson5802** [jimthompson5802/datascience_containers#25]

**Comment by jimthompson5802** [comment]
Initial attempt at image build failed on MacOS.  May have to build image on AWS gpu-enabled ec2 instance with Deep Learning framework.

**Comment by jimthompson5802** [comment]
Made some progress.  
* Using base image `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`.  
* To enable use  of nvidia-docker2 extensions had to modify `/etc/docker/daemon.json` to change default runtime to `"default-runtime": "nvidia"`
* Built Anaconda3 with version 4.3.1 to get Python 3.6 to meet TensorFlow 1.11 requirement.

Current problem is that the Anaconda environment built missing some files:
```
[ec2-user@ip-172-31-41-208 tfgpu]$ docker-compose run --rm tfgpu /bin/bash
WARNING: The NOTEBOOK_PASSWORD variable is not set. Defaulting to a blank string.
bash: /opt/conda/etc/profile.d/conda.sh: No such file or directory
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 161, in main
    raise CommandNotFoundError(argv1, message)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

Still researching.

**Comment by jimthompson5802** [comment]
Resolved notebook server start issue by using [tensorflow/tensorflow docker images](https://www.tensorflow.org/install/docker):
* tensorflow/tensorflow:latest-py3
* tensorflow/tensorflow:latest-gpu-py3

Tested both images on MacOS and AWS p2.xlarge instance.  Saw significant reduction in run-time with the gpu version of TF.

On issue still outstanding:  setting permissions for the /my_workarea directory in container.

**Comment by jimthompson5802** [comment]
Found additional information on file permission issue.  See [posting](
https://github.com/jimthompson5802/datascience_containers/wiki/File-Permission-Issues-With-Containers-on-MacOS-vs-Linux).

**Comment by jimthompson5802** [comment]
Done.  commit: e5fe09a3a67f88c39632327452a539c807d91063
